"use client";

import { use, useEffect, useState } from "react";
import { Loader2, PlayCircle, Eye, Sparkles, Calendar, Zap, Film, CheckCircle2, AlertTriangle, RefreshCw, Facebook } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { MarkdownContent } from "@/components/markdown-content";
import Link from "next/link";

function formatNumber(n: number): string {
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1).replace(/\.0$/, "") + "M";
  if (n >= 1_000) return (n / 1_000).toFixed(1).replace(/\.0$/, "") + "K";
  return n.toLocaleString();
}

function normalizeMarkdown(text: string) {
  if (!text) return text;
  // Replace single newlines with double newlines for proper paragraph breaks
  // but avoid replacing double newlines with quadruple newlines
  return text.replace(/([^\n])\n([^\n])/g, '$1\n\n$2');
}

export default function PublicAdReportPage({ params }: { params: Promise<{ profileUrl: string }> }) {
  const resolvedParams = use(params);
  const profileUrl = decodeURIComponent(resolvedParams.profileUrl);

  const [report, setReport] = useState<any>(null);
  const [ads, setAds] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadData() {
      try {
        setLoading(true);
        const encodedUrl = encodeURIComponent(profileUrl);
        const [cRes, pRes] = await Promise.all([
          fetch(`/api/facebook-ads/public-report?profileUrl=${encodedUrl}`),
          fetch(`/api/facebook-ads/public-ads?profileUrl=${encodedUrl}`)
        ]);

        if (!cRes.ok) throw new Error("Report not found or not public");
        
        const cData = await cRes.json();
        setReport(cData.report);

        if (pRes.ok) {
          const pData = await pRes.json();
          setAds(pData);
        }
      } catch (err: any) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }
    loadData();
  }, [profileUrl]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[80vh]">
        <Loader2 className="h-8 w-8 animate-spin text-blue-500" />
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[80vh] text-center space-y-4">
        <AlertTriangle className="h-12 w-12 text-red-500" />
        <h2 className="text-2xl font-bold">Report Not Found</h2>
        <p className="text-muted-foreground">{error || "This competitor analysis does not exist or is not public."}</p>
        <Button asChild className="mt-4"><Link href="/">Go to Homepage</Link></Button>
      </div>
    );
  }

  const getMediaUrl = (ad: any) => {
    if (ad.displayFormat === "VIDEO" && ad.videos && ad.videos.length > 0) {
      return ad.videos[0].videoHdUrl || ad.videos[0].videoSdUrl || null;
    }
    if (ad.images && ad.images.length > 0) {
      return ad.images[0].originalImageUrl || ad.images[0].resizedImageUrl || null;
    }
    return null;
  };

  const getPreviewUrl = (ad: any) => {
    if (ad.displayFormat === "VIDEO" && ad.videos && ad.videos.length > 0) {
      return ad.videos[0].videoPreviewImageUrl || null;
    }
    return getMediaUrl(ad);
  };

  const dataAgeHours = report.generatedAt ? Math.max(1, Math.round((Date.now() - new Date(report.generatedAt).getTime()) / (1000 * 60 * 60))) : 0;
  const pageName = report.pageName || profileUrl.split('?')[0].split('/').pop() || "Brand";

  return (
    <div className="max-w-5xl mx-auto space-y-12 pb-20 pt-6 px-4 animate-in fade-in duration-500">
      
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row items-center justify-between bg-gradient-to-r from-blue-500/10 to-violet-500/10 border border-blue-500/20 rounded-2xl p-4 sm:p-6 gap-4 text-center sm:text-left">
        <div>
          <h1 className="text-xl sm:text-2xl font-black text-foreground">Competitor Ad Intelligence</h1>
          <p className="text-sm text-muted-foreground mt-1">Generated by The Hook Lab's AI Engine</p>
        </div>
        <Button asChild className="bg-blue-600 hover:bg-blue-700 text-white rounded-xl shadow-lg shadow-blue-500/20 shrink-0">
          <Link href="/">Try The Hook Lab Free</Link>
        </Button>
      </div>

      {/* Trust Metadata */}
      <div className="flex flex-wrap items-center justify-center gap-4 text-xs font-medium text-muted-foreground">
        <div className="flex items-center gap-1.5 bg-muted/50 px-3 py-1.5 rounded-full border border-border/40">
          <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" /> Report Verified
        </div>
        <div className="flex items-center gap-1.5 bg-muted/50 px-3 py-1.5 rounded-full border border-border/40">
          <Calendar className="h-3.5 w-3.5" /> Generated: {report.generatedAt ? new Date(report.generatedAt).toLocaleDateString() : 'Recently'}
        </div>
        <div className="flex items-center gap-1.5 bg-muted/50 px-3 py-1.5 rounded-full border border-border/40">
          <RefreshCw className="h-3.5 w-3.5" /> Data Age: {dataAgeHours} hours
        </div>
        <div className="flex items-center gap-1.5 bg-muted/50 px-3 py-1.5 rounded-full border border-border/40">
          <Film className="h-3.5 w-3.5" /> Analyzed: {ads.length}+ ads
        </div>
      </div>

      {/* Hero Profile Section */}
      <div className="relative rounded-3xl overflow-hidden border border-border/50 bg-card shadow-sm">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-500/5 via-transparent to-transparent opacity-50" />
        <div className="relative p-6 sm:p-10 flex flex-col items-center sm:items-start text-center sm:text-left gap-4">
          <div className="flex items-center gap-3 mb-2">
            <div className="h-12 w-12 rounded-xl bg-blue-500/20 border border-blue-500/30 flex items-center justify-center">
              <Facebook className="h-6 w-6 text-blue-500" />
            </div>
            <div>
              <h1 className="text-3xl sm:text-4xl font-black tracking-tight flex items-center gap-2">
                {pageName} <Sparkles className="h-6 w-6 text-blue-500 fill-blue-500/20" />
              </h1>
              <p className="text-sm text-muted-foreground max-w-xl truncate">{profileUrl}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Main AI Markdown Report */}
      {report.reportMarkdown && (
        <div className="space-y-4">
          <h2 className="text-2xl sm:text-3xl font-black flex items-center gap-2 text-center sm:text-left">
            <Sparkles className="h-6 w-6 text-blue-500" /> Ad Strategy Breakdown
          </h2>
          <div className="rounded-3xl border border-border/50 bg-card p-6 sm:p-10 shadow-sm overflow-x-auto">
            <MarkdownContent content={normalizeMarkdown(report.reportMarkdown)} variant="analysis" />
          </div>
        </div>
      )}

      {/* Top Ads Sample */}
      {ads.length > 0 && (
        <div className="space-y-6 pt-10 border-t border-border/30">
          <h2 className="text-2xl font-black flex items-center gap-2"><PlayCircle className="h-6 w-6 text-blue-500" /> Sample Active Ads</h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
            {ads.slice(0, 8).map((ad) => {
              const preview = getPreviewUrl(ad);
              const media = getMediaUrl(ad);
              const isVideo = ad.displayFormat === "VIDEO";
              return (
                <div key={ad.adArchiveId} className="relative aspect-square sm:aspect-[4/5] bg-muted/50 overflow-hidden rounded-xl group border border-border/40 shadow-sm">
                  {preview ? (
                    <img src={`/api/proxy-image?url=${encodeURIComponent(preview)}`} alt="Ad" className="w-full h-full object-cover" />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center"><Film className="h-8 w-8 text-muted-foreground/30" /></div>
                  )}
                  {isVideo && (
                    <div className="absolute top-2 right-2 bg-black/60 backdrop-blur-md rounded-md px-1.5 py-0.5 flex items-center">
                      <PlayCircle className="h-3 w-3 text-white mr-1" /> <span className="text-[10px] text-white font-medium">Video</span>
                    </div>
                  )}
                  <div className="absolute bottom-0 left-0 right-0 p-3 bg-gradient-to-t from-black/80 to-transparent">
                    {ad.ctaText && (
                      <span className="text-white font-bold text-xs bg-blue-600 px-2 py-0.5 rounded shadow-md uppercase">
                        {ad.ctaText.replace(/_/g, " ")}
                      </span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Viral Growth Loop CTA */}
      <div className="mt-16 bg-gradient-to-br from-blue-600 to-violet-600 rounded-3xl p-8 sm:p-12 text-center text-white shadow-2xl relative overflow-hidden">
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay"></div>
        <div className="relative z-10 max-w-2xl mx-auto space-y-6">
          <h2 className="text-3xl sm:text-4xl font-black">Want to analyze your competitor's ads?</h2>
          <p className="text-lg text-white/80 font-medium">Stop guessing what works. Discover the exact creatives, funnels, and hooks your competitors are using to scale.</p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4">
            <Button asChild size="lg" className="bg-white text-blue-700 hover:bg-gray-50 rounded-xl h-14 px-8 text-base font-bold w-full sm:w-auto shadow-xl">
              <Link href="/">Start Free Analysis</Link>
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
