"use client";
import { use, useEffect, useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Sparkles,
  Video,
  Scissors,
  Wand2,
  Heart,
  MessageCircle,
  Play,
  Save,
  FileText,
  Loader2,
  AlertTriangle
} from "lucide-react";
import { MarkdownContent } from "@/components/markdown-content";
import Link from "next/link";
import type { ReelAnalysisResult } from "@/lib/types";

function formatViews(n: number): string {
  if (n === undefined || n === null) return "0";
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1).replace(/\.0$/, "") + "M";
  if (n >= 1_000) return (n / 1_000).toFixed(1).replace(/\.0$/, "") + "K";
  return n.toString();
}

type TabType = "analysis" | "concepts" | "director" | "editor" | "recreate" | "script";

export default function PublicReelReportPage({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = use(params);
  const id = resolvedParams.id;

  const [result, setResult] = useState<ReelAnalysisResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<TabType>("analysis");

  useEffect(() => {
    async function loadData() {
      try {
        setLoading(true);
        const res = await fetch(`/api/instagram/reel-analyzer/public/${id}`);
        if (!res.ok) throw new Error("Report not found or not public");
        
        const data = await res.json();
        
        setResult({
          id: data.id,
          metadata: {
            creator: `@${data.creator}`,
            caption: data.caption,
            views: data.views,
            likes: data.likes,
            comments: data.comments,
            duration: data.duration,
            thumbnail: data.thumbnailUrl,
            reelUrl: data.reelUrl,
          },
          analysis: data.analysis,
          newConcepts: data.newConcepts,
          directorMode: data.directorMode,
          editorMode: data.editorMode,
          recreationGuide: data.recreationGuide,
          script: data.script,
        });
      } catch (err: any) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }
    loadData();
  }, [id]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[80vh]">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  if (error || !result) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[80vh] text-center space-y-4">
        <AlertTriangle className="h-12 w-12 text-destructive" />
        <h2 className="text-2xl font-bold">Report Not Found</h2>
        <p className="text-muted-foreground">{error || "This reel analysis does not exist or is not public."}</p>
        <Button asChild className="mt-4"><Link href="/">Go to Homepage</Link></Button>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto space-y-8 pb-20 pt-6 px-4 animate-in fade-in duration-500">
      
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row items-center justify-between bg-gradient-to-r from-primary/10 to-destructive/10 border border-primary/20 rounded-2xl p-4 sm:p-6 gap-4 text-center sm:text-left">
        <div>
          <h1 className="text-xl sm:text-2xl font-black text-foreground">Viral Reel Intelligence</h1>
          <p className="text-sm text-muted-foreground mt-1">Deep analysis generated by The Hook Lab</p>
        </div>
        <Button asChild className="bg-gradient-to-r from-primary to-destructive hover:from-primary hover:to-destructive text-primary-foreground rounded-xl shadow-lg shadow-primary/20 shrink-0">
          <Link href="/">Try The Hook Lab Free</Link>
        </Button>
      </div>

      <div className="flex flex-col gap-6">
        {/* Metadata Card */}
        <Card className="p-4 rounded-2xl bg-background/40 backdrop-blur-md border-border/40 shadow-xl overflow-hidden relative">
          <div className="absolute inset-0 bg-gradient-to-br from-primary/5 to-destructive/5 pointer-events-none" />
          <div className="flex flex-col md:flex-row gap-6 items-start relative z-10">
            {/* Thumbnail */}
            <div className="relative w-full md:w-32 aspect-[9/16] rounded-xl overflow-hidden bg-muted border border-border/50 shadow-inner flex-shrink-0 group">
              {result.metadata.thumbnail ? (
                <img
                  src={`/api/proxy-image?url=${encodeURIComponent(result.metadata.thumbnail)}`}
                  alt="Reel thumbnail"
                  className="absolute inset-0 w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                />
              ) : (
                <div className="absolute inset-0 flex items-center justify-center">
                  <Video className="h-8 w-8 text-muted-foreground/30" />
                </div>
              )}
              <div className="absolute inset-0 bg-black/20 group-hover:bg-black/0 transition-colors duration-300" />
              <a
                href={result.metadata.reelUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300"
              >
                <div className="h-12 w-12 rounded-full bg-black/50 backdrop-blur-sm flex items-center justify-center text-white border border-white/20">
                  <Play className="h-5 w-5 ml-1" />
                </div>
              </a>
              {result.metadata.duration && (
                <div className="absolute bottom-2 right-2 px-2 py-1 rounded bg-black/60 backdrop-blur-md text-white text-[10px] font-medium tracking-wide">
                  {result.metadata.duration}
                </div>
              )}
            </div>

            {/* Info */}
            <div className="flex-1 flex flex-col h-full w-full">
              <div className="flex items-start justify-between mb-2">
                <div className="flex items-center gap-2">
                  <div className="h-8 w-8 rounded-full bg-gradient-to-br from-primary/20 to-destructive/20 flex items-center justify-center border border-primary/30">
                    <span className="text-xs font-bold text-primary dark:text-primary">
                      {result.metadata.creator.charAt(1).toUpperCase()}
                    </span>
                  </div>
                  <span className="font-bold text-lg text-foreground">{result.metadata.creator}</span>
                </div>
              </div>

              <div className="flex gap-4 mb-4 mt-2">
                <Badge variant="secondary" className="px-3 py-1 text-xs font-medium bg-info/10 text-info dark:text-info border-info/20 rounded-lg flex gap-1.5 items-center">
                  <Play className="h-3.5 w-3.5" />
                  {formatViews(result.metadata.views)} Views
                </Badge>
                <Badge variant="secondary" className="px-3 py-1 text-xs font-medium bg-destructive/10 text-destructive dark:text-destructive border-destructive/20 rounded-lg flex gap-1.5 items-center">
                  <Heart className="h-3.5 w-3.5" />
                  {formatViews(result.metadata.likes)}
                </Badge>
                <Badge variant="secondary" className="px-3 py-1 text-xs font-medium bg-success/10 text-success dark:text-success border-success/20 rounded-lg flex gap-1.5 items-center">
                  <MessageCircle className="h-3.5 w-3.5" />
                  {formatViews(result.metadata.comments)}
                </Badge>
              </div>

              <div className="bg-muted/30 rounded-xl p-3 border border-border/30 max-h-[120px] overflow-y-auto mt-auto">
                <p className="text-sm text-foreground/80 line-clamp-4 leading-relaxed">
                  {result.metadata.caption || "No caption."}
                </p>
              </div>
            </div>
          </div>
        </Card>

        {/* Deep Analysis Tabs */}
        <div className="bg-background/40 backdrop-blur-md rounded-2xl border border-border/40 shadow-xl overflow-hidden flex flex-col md:flex-row min-h-[400px]">
          {/* Vertical Tab Navigation */}
          <div className="w-full md:w-56 lg:w-64 border-b md:border-b-0 md:border-r border-border/30 p-4 flex md:flex-col gap-2 overflow-x-auto md:overflow-visible shrink-0 bg-muted/10">
            <h3 className="hidden md:block text-xs font-bold tracking-wider text-muted-foreground uppercase mb-2 px-2">Deep Analysis</h3>

            <button
              onClick={() => setActiveTab("analysis")}
              className={`flex items-center gap-3 px-3 py-3 rounded-xl transition-all duration-200 uppercase tracking-wide text-xs font-bold text-left min-w-[140px] md:min-w-0 ${activeTab === "analysis"
                ? "bg-primary/10 text-primary dark:text-primary border border-primary/20 shadow-sm"
                : "text-muted-foreground hover:bg-muted/50 hover:text-foreground border border-transparent"
                }`}
            >
              <Sparkles className="h-4 w-4" />
              Analysis
            </button>

            <button
              onClick={() => setActiveTab("concepts")}
              className={`flex items-center gap-3 px-3 py-3 rounded-xl transition-all duration-200 uppercase tracking-wide text-xs font-bold text-left min-w-[140px] md:min-w-0 ${activeTab === "concepts"
                ? "bg-warning/10 text-warning dark:text-warning border border-warning/20 shadow-sm"
                : "text-muted-foreground hover:bg-muted/50 hover:text-foreground border border-transparent"
                }`}
            >
              <Wand2 className="h-4 w-4" />
              New Concepts
            </button>

            <div className="hidden md:block my-2 border-t border-border/20" />

            <button
              onClick={() => setActiveTab("director")}
              className={`flex items-center gap-3 px-3 py-3 rounded-xl transition-all duration-200 uppercase tracking-wide text-xs font-bold text-left min-w-[140px] md:min-w-0 ${activeTab === "director"
                ? "bg-info/10 text-info dark:text-info border border-info/20 shadow-sm"
                : "text-muted-foreground hover:bg-muted/50 hover:text-foreground border border-transparent"
                }`}
            >
              <Video className="h-4 w-4" />
              Director Mode
            </button>

            <button
              onClick={() => setActiveTab("editor")}
              className={`flex items-center gap-3 px-3 py-3 rounded-xl transition-all duration-200 uppercase tracking-wide text-xs font-bold text-left min-w-[140px] md:min-w-0 ${activeTab === "editor"
                ? "bg-success/10 text-success dark:text-success border border-success/20 shadow-sm"
                : "text-muted-foreground hover:bg-muted/50 hover:text-foreground border border-transparent"
                }`}
            >
              <Scissors className="h-4 w-4" />
              Editor Mode
            </button>

            <div className="hidden md:block my-2 border-t border-border/20" />

            <button
              onClick={() => setActiveTab("recreate")}
              className={`flex items-center gap-3 px-3 py-3 rounded-xl transition-all duration-200 uppercase tracking-wide text-xs font-bold text-left min-w-[140px] md:min-w-0 ${activeTab === "recreate"
                ? "bg-destructive/10 text-destructive dark:text-destructive border border-destructive/20 shadow-sm"
                : "text-muted-foreground hover:bg-muted/50 hover:text-foreground border border-transparent"
                }`}
            >
              <Save className="h-4 w-4" />
              Recreate Blueprint
            </button>

            <button
              onClick={() => setActiveTab("script")}
              className={`flex items-center gap-3 px-3 py-3 rounded-xl transition-all duration-200 uppercase tracking-wide text-xs font-bold text-left min-w-[140px] md:min-w-0 ${activeTab === "script"
                ? "bg-info/10 text-info dark:text-info border border-info/20 shadow-sm"
                : "text-muted-foreground hover:bg-muted/50 hover:text-foreground border border-transparent"
                }`}
            >
              <FileText className="h-4 w-4" />
              Video Script
            </button>
          </div>

          {/* Tab Content Area */}
          <div className="flex-1 p-4 md:p-6 overflow-y-auto max-h-[800px] min-h-[400px]">

            {/* === ANALYSIS === */}
            {activeTab === "analysis" && (
              <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
                <div className="flex items-center gap-3 mb-6">
                  <div className="p-2 rounded-lg bg-primary/10 text-primary border border-primary/20">
                    <Sparkles className="h-5 w-5" />
                  </div>
                  <h2 className="text-2xl font-bold">Reel Analysis</h2>
                </div>
                <div className="prose dark:prose-invert max-w-none bg-muted/20 p-6 rounded-2xl border border-border/30">
                  <MarkdownContent content={result.analysis || "Analysis not available for this reel."} />
                </div>
              </div>
            )}

            {/* === NEW CONCEPTS === */}
            {activeTab === "concepts" && (
              <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
                <div className="flex items-center gap-3 mb-6">
                  <div className="p-2 rounded-lg bg-warning/10 text-warning border border-warning/20">
                    <Wand2 className="h-5 w-5" />
                  </div>
                  <h2 className="text-2xl font-bold">New Reel Concepts</h2>
                </div>
                <div className="prose dark:prose-invert max-w-none bg-muted/20 p-6 rounded-2xl border border-border/30">
                  <MarkdownContent content={result.newConcepts || "No concepts generated for this reel."} />
                </div>
              </div>
            )}

            {/* === DIRECTOR MODE === */}
            {activeTab === "director" && (
              <div className="space-y-8 animate-in fade-in slide-in-from-right-4 duration-300">
                <div className="flex items-center gap-3 mb-6">
                  <div className="p-2 rounded-lg bg-info/10 text-info border border-info/20">
                    <Video className="h-5 w-5" />
                  </div>
                  <h2 className="text-2xl font-bold">Director's Breakdown</h2>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="bg-muted/30 p-4 rounded-xl border border-border/30">
                    <div className="text-xs uppercase tracking-wider text-muted-foreground font-bold mb-2">Shot Types</div>
                    <div className="text-sm"><MarkdownContent content={result.directorMode?.shotTypes || "-"} /></div>
                  </div>
                  <div className="bg-muted/30 p-4 rounded-xl border border-border/30">
                    <div className="text-xs uppercase tracking-wider text-muted-foreground font-bold mb-2">Angles</div>
                    <div className="text-sm"><MarkdownContent content={result.directorMode?.cameraAngles || "-"} /></div>
                  </div>
                  <div className="bg-muted/30 p-4 rounded-xl border border-border/30">
                    <div className="text-xs uppercase tracking-wider text-muted-foreground font-bold mb-2">Movement</div>
                    <div className="text-sm"><MarkdownContent content={result.directorMode?.cameraMovement || "-"} /></div>
                  </div>
                  <div className="bg-muted/30 p-4 rounded-xl border border-border/30">
                    <div className="text-xs uppercase tracking-wider text-muted-foreground font-bold mb-2">Lighting</div>
                    <div className="text-sm"><MarkdownContent content={result.directorMode?.lightingStyle || "-"} /></div>
                  </div>
                </div>

                <div className="bg-muted/30 p-5 rounded-2xl border border-border/30">
                  <h4 className="text-sm font-bold uppercase tracking-wider text-muted-foreground mb-3">Composition</h4>
                  <MarkdownContent content={result.directorMode?.sceneComposition || "-"} />
                </div>

                <div className="bg-info/5 p-6 rounded-2xl border border-info/20">
                  <div className="flex items-center gap-2 mb-4">
                    <Video className="h-5 w-5 text-info" />
                    <h4 className="text-lg font-bold text-foreground">Shooting Guide</h4>
                  </div>
                  <div className="prose-sm md:prose dark:prose-invert">
                    <MarkdownContent content={result.directorMode?.shootingGuide || "No shooting guide available."} />
                  </div>
                </div>
              </div>
            )}

            {/* === EDITOR MODE === */}
            {activeTab === "editor" && (
              <div className="space-y-8 animate-in fade-in slide-in-from-right-4 duration-300">
                <div className="flex items-center gap-3 mb-6">
                  <div className="p-2 rounded-lg bg-success/10 text-success border border-success/20">
                    <Scissors className="h-5 w-5" />
                  </div>
                  <h2 className="text-2xl font-bold">Editor's Guide</h2>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="bg-muted/30 p-5 rounded-2xl border border-border/30">
                    <h4 className="text-sm font-bold uppercase tracking-wider text-muted-foreground mb-3">Cuts & Pacing</h4>
                    <MarkdownContent content={`**Style:** ${result.editorMode?.cutStyle || "-"}\n\n**Timing:** ${result.editorMode?.timingPacing || "-"}`} />
                  </div>

                  <div className="bg-muted/30 p-5 rounded-2xl border border-border/30">
                    <h4 className="text-sm font-bold uppercase tracking-wider text-muted-foreground mb-3">Visuals & Text</h4>
                    <MarkdownContent content={`**Effects:** ${result.editorMode?.effectsUsed || "-"}\n\n**Text:** ${result.editorMode?.textAnimation || "-"}`} />
                  </div>

                  <div className="bg-muted/30 p-5 rounded-2xl border border-border/30 md:col-span-2">
                    <h4 className="text-sm font-bold uppercase tracking-wider text-muted-foreground mb-3">Sound Design</h4>
                    <MarkdownContent content={result.editorMode?.soundDesign || "-"} />
                  </div>

                  <div className="bg-success/5 p-5 rounded-2xl border border-success/20 md:col-span-2">
                    <h4 className="text-sm font-bold uppercase tracking-wider text-success dark:text-success mb-3">Toolkit Requirements</h4>
                    <MarkdownContent content={`**Software:** ${result.editorMode?.suggestedTools || "Any modern video editor"}\n\n**Plugins/Assets:** ${result.editorMode?.pluginsPresets || "None specific"}`} />
                  </div>
                </div>
              </div>
            )}

            {/* === RECREATE BLUEPRINT === */}
            {activeTab === "recreate" && (
              <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
                <div className="flex items-center gap-3 mb-6">
                  <div className="p-2 rounded-lg bg-destructive/10 text-destructive border border-destructive/20">
                    <Save className="h-5 w-5" />
                  </div>
                  <h2 className="text-2xl font-bold">Recreate Blueprint</h2>
                </div>
                
                <div className="grid grid-cols-1 xl:grid-cols-2 gap-6 items-start">
                  {/* Beginner Box */}
                  <div className="bg-gradient-to-b from-info/5 to-transparent p-6 rounded-2xl border border-info/20">
                    <h3 className="text-lg font-bold text-info dark:text-info mb-4 flex items-center gap-2 border-b border-info/10 pb-3">
                      <span className="bg-info/20 p-1.5 rounded-md">1</span>
                      Beginner Fast-Track
                    </h3>
                    <div className="prose-sm md:prose dark:prose-invert max-w-none">
                      <MarkdownContent content={result.recreationGuide?.beginnerVersion || "Beginner guide not available."} />
                    </div>
                  </div>

                  {/* Pro Box */}
                  <div className="bg-gradient-to-b from-primary/5 to-transparent p-6 rounded-2xl border border-primary/20">
                    <h3 className="text-lg font-bold text-primary dark:text-primary mb-4 flex items-center gap-2 border-b border-primary/10 pb-3">
                      <span className="bg-primary/20 p-1.5 rounded-md">2</span>
                      Advanced / Pro Workflow
                    </h3>
                    <div className="prose-sm md:prose dark:prose-invert max-w-none">
                      <MarkdownContent content={result.recreationGuide?.advancedVersion || "Pro guide not available."} />
                    </div>
                  </div>
                </div>

                {/* Brand Adaptation */}
                <div className="bg-destructive/5 p-6 rounded-2xl border border-destructive/20 mt-4">
                  <h3 className="text-xl font-bold text-destructive dark:text-destructive mb-4">
                    Adapt to Your Brand
                  </h3>
                  <div className="text-lg leading-relaxed">
                    <MarkdownContent content={result.recreationGuide?.adaptToYourBrand || "Adaptation guide not available."} />
                  </div>
                </div>
              </div>
            )}

            {/* === VIDEO SCRIPT === */}
            {activeTab === "script" && (
              <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
                <div className="flex items-center gap-3 mb-6">
                  <div className="p-2 rounded-lg bg-info/10 text-info border border-info/20">
                    <FileText className="h-5 w-5" />
                  </div>
                  <h2 className="text-2xl font-bold">Video Script</h2>
                </div>
                <div className="prose dark:prose-invert max-w-none bg-muted/20 p-6 rounded-2xl border border-border/30">
                  <MarkdownContent content={result.script || "Script not generated."} />
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
