"use client";

import { use, useEffect, useState } from "react";
import { Loader2, PlayCircle, Heart, Eye, Sparkles, TrendingUp, Calendar, Zap, Instagram, Film, Users, CheckCircle2, AlertTriangle, RefreshCw } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { MarkdownContent } from "@/components/markdown-content";
import { calculateGrowthPace } from "@/lib/growth-pace";
import Link from "next/link";

function formatNumber(n: number): string {
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1).replace(/\.0$/, "") + "M";
  if (n >= 1_000) return (n / 1_000).toFixed(1).replace(/\.0$/, "") + "K";
  return n.toLocaleString();
}

export default function PublicReportPage({ params }: { params: Promise<{ username: string }> }) {
  const resolvedParams = use(params);
  const username = resolvedParams.username;

  const [creator, setCreator] = useState<any>(null);
  const [posts, setPosts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadData() {
      try {
        setLoading(true);
        const [cRes, pRes] = await Promise.all([
          fetch(`/api/instagram/public-report/${username}`),
          fetch(`/api/instagram/public-posts/${username}`)
        ]);

        if (!cRes.ok) throw new Error("Creator not found or not public");
        
        const cData = await cRes.json();
        setCreator(cData);

        if (pRes.ok) {
          const pData = await pRes.json();
          setPosts(pData);
        }
      } catch (err: any) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }
    loadData();
  }, [username]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[80vh]">
        <Loader2 className="h-8 w-8 animate-spin text-orange-500" />
      </div>
    );
  }

  if (error || !creator) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[80vh] text-center space-y-4">
        <AlertTriangle className="h-12 w-12 text-red-500" />
        <h2 className="text-2xl font-bold">Report Not Found</h2>
        <p className="text-muted-foreground">{error || "This creator analysis does not exist or is not public."}</p>
        <Button asChild className="mt-4"><Link href="/">Go to Homepage</Link></Button>
      </div>
    );
  }

  const topPerformances = posts
    .filter(p => p.videoPlayCount > (creator.avgViews30d || 0))
    .sort((a, b) => b.videoPlayCount - a.videoPlayCount)
    .slice(0, 10);

  const growthPace = calculateGrowthPace({
    reels: posts.map((p: any) => ({
      id: (p.postId || p.id || Math.random()).toString(),
      views: p.videoPlayCount || 0,
      likes: p.likesCount || 0,
      comments: p.commentsCount || 0,
      postedAt: p.timestamp || p.postedAt || p.createdAt
    })),
    now: new Date()
  });

  const getStatusColors = (status: string) => {
    switch(status) {
      case "Explosive":
      case "Rising Fast": return "text-emerald-500 bg-emerald-500/10 border-emerald-500/20";
      case "Steady Growth": return "text-emerald-400 bg-emerald-400/10 border-emerald-400/20";
      case "High-Volume Push": return "text-blue-500 bg-blue-500/10 border-blue-500/20";
      case "Cooling Down": return "text-orange-500 bg-orange-500/10 border-orange-500/20";
      case "Dormant": return "text-red-500 bg-red-500/10 border-red-500/20";
      case "Early Weak Signal": return "text-yellow-500 bg-yellow-500/10 border-yellow-500/20";
      default: return "text-muted-foreground bg-muted/30 border-border/50";
    }
  };

  const dataAgeHours = creator.generatedAt ? Math.max(1, Math.round((Date.now() - new Date(creator.generatedAt).getTime()) / (1000 * 60 * 60))) : 0;

  return (
    <div className="max-w-5xl mx-auto space-y-12 pb-20 pt-6 px-4 animate-in fade-in duration-500">
      
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row items-center justify-between bg-gradient-to-r from-orange-500/10 to-rose-500/10 border border-orange-500/20 rounded-2xl p-4 sm:p-6 gap-4 text-center sm:text-left">
        <div>
          <h1 className="text-xl sm:text-2xl font-black text-foreground">Creator Intelligence Report</h1>
          <p className="text-sm text-muted-foreground mt-1">Generated by The Hook Lab's AI Engine</p>
        </div>
        <Button asChild className="bg-orange-500 hover:bg-orange-600 text-white rounded-xl shadow-lg shadow-orange-500/20 shrink-0">
          <Link href="/">Try The Hook Lab Free</Link>
        </Button>
      </div>

      {/* Trust Metadata */}
      <div className="flex flex-wrap items-center justify-center gap-4 text-xs font-medium text-muted-foreground">
        <div className="flex items-center gap-1.5 bg-muted/50 px-3 py-1.5 rounded-full border border-border/40">
          <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" /> Report Verified
        </div>
        <div className="flex items-center gap-1.5 bg-muted/50 px-3 py-1.5 rounded-full border border-border/40">
          <Calendar className="h-3.5 w-3.5" /> Generated: {creator.generatedAt ? new Date(creator.generatedAt).toLocaleDateString() : 'Recently'}
        </div>
        <div className="flex items-center gap-1.5 bg-muted/50 px-3 py-1.5 rounded-full border border-border/40">
          <RefreshCw className="h-3.5 w-3.5" /> Data Age: {dataAgeHours} hours
        </div>
        <div className="flex items-center gap-1.5 bg-muted/50 px-3 py-1.5 rounded-full border border-border/40">
          <Film className="h-3.5 w-3.5" /> Analyzed: {posts.length} posts
        </div>
      </div>

      {/* Hero Profile Section */}
      <div className="relative rounded-3xl overflow-hidden border border-border/50 bg-card shadow-sm">
        <div className="absolute inset-0 bg-gradient-to-br from-orange-500/5 via-transparent to-transparent opacity-50" />
        <div className="relative p-6 sm:p-10 flex flex-col sm:flex-row items-center sm:items-start gap-6 sm:gap-8">
          <div className="w-24 h-24 sm:w-32 sm:h-32 rounded-full overflow-hidden border-4 border-background shadow-xl shrink-0 flex items-center justify-center bg-muted">
            {creator.profilePicUrl ? (
              <img
                src={`/api/proxy-image?url=${encodeURIComponent(creator.profilePicUrl)}`}
                alt={creator.username}
                className="w-full h-full object-cover"
              />
            ) : (
              <span className="text-4xl font-bold opacity-30">{creator.username.charAt(0).toUpperCase()}</span>
            )}
          </div>

          <div className="flex flex-col items-center sm:items-start text-center sm:text-left flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <h1 className="text-3xl sm:text-4xl font-black tracking-tight truncate">@{creator.username}</h1>
              {creator.aiInsights && <Sparkles className="h-5 w-5 text-orange-400 fill-orange-400/20" />}
            </div>
            {creator.name && <span className="text-lg font-medium text-muted-foreground mb-3 block">{creator.name}</span>}
            <Badge variant="secondary" className="bg-orange-500/10 text-orange-600 hover:bg-orange-500/20 border-orange-500/20 mb-4">{creator.category}</Badge>
            <p className="text-sm text-muted-foreground max-w-2xl leading-relaxed whitespace-pre-wrap">{creator.bio}</p>
          </div>

          <div className="w-full sm:w-auto grid grid-cols-2 gap-3 shrink-0">
            <div className="flex flex-col items-center justify-center p-4 bg-muted/40 rounded-2xl border border-border/40">
              <span className="text-2xl font-bold text-foreground">{formatNumber(creator.followersCount || 0)}</span>
              <span className="text-xs font-medium text-muted-foreground uppercase tracking-wider mt-1">Followers</span>
            </div>
            <div className="flex flex-col items-center justify-center p-4 bg-muted/40 rounded-2xl border border-border/40">
              <span className="text-2xl font-bold text-foreground">{formatNumber(creator.totalPosts || 0)}</span>
              <span className="text-xs font-medium text-muted-foreground uppercase tracking-wider mt-1">Posts</span>
            </div>
          </div>
        </div>
      </div>

      {/* Growth Pace */}
      <div className={`rounded-3xl p-6 sm:p-8 border ${getStatusColors(growthPace.status)} flex flex-col md:flex-row gap-8 items-start shadow-sm`}>
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-2">
            <TrendingUp className="h-5 w-5" />
            <span className="text-sm font-bold uppercase tracking-wider opacity-80">Growth Pace Estimate</span>
          </div>
          <div className="flex items-end gap-3 mb-3">
            <span className="text-3xl sm:text-4xl font-black">{growthPace.status}</span>
            {growthPace.score !== null && <span className="text-xl font-bold opacity-75 mb-1">{growthPace.score}/100</span>}
          </div>
          <div className="flex items-center gap-2 text-sm font-medium">
            <span className="bg-background/50 px-3 py-1.5 rounded-lg opacity-90">Driver: {growthPace.driver}</span>
          </div>
        </div>
        <div className="flex-1 w-full bg-background/30 rounded-2xl p-5 border border-current/10">
          <span className="text-xs font-bold uppercase tracking-wider opacity-70 mb-3 block">Analysis</span>
          <ul className="space-y-3 text-sm font-medium">
            {growthPace.reasons.map((reason, idx) => (
              <li key={idx} className="flex items-start gap-3">
                <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-current opacity-60 flex-shrink-0" />
                <span className="opacity-90 leading-relaxed">{reason}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* AI Insights */}
      {creator.aiInsights ? (
        <div className="space-y-8">
          <div className="text-center space-y-2 mb-8">
            <h2 className="text-2xl sm:text-3xl font-black flex items-center justify-center gap-2">
              <Sparkles className="h-6 w-6 text-orange-500" /> Deep AI Breakdown
            </h2>
            <p className="text-muted-foreground">The exact strategy, hooks, and flaws extracted by our engine.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card className="shadow-sm border-border/40">
              <CardHeader>
                <CardTitle className="text-lg flex items-center gap-2"><TrendingUp className="h-5 w-5 text-emerald-500" /> Success Factors</CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-4">
                  {creator.aiInsights?.successFactors?.map((reason: string, i: number) => (
                    <li key={i} className="flex gap-3 text-sm">
                      <span className="flex shrink-0 w-6 h-6 items-center justify-center rounded-full bg-emerald-500/10 text-emerald-600 font-bold text-xs">{i + 1}</span>
                      <span className="pt-0.5 leading-relaxed font-medium text-foreground/80">{reason}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            <div className="space-y-6 flex flex-col">
              <Card className="shadow-sm border-border/40 flex-1">
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2"><Film className="h-5 w-5 text-blue-500" /> Content Themes</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2">
                    {creator.aiInsights?.contentThemes?.map((theme: string, i: number) => (
                      <Badge key={i} variant="secondary" className="px-3 py-1.5 bg-blue-500/10 text-blue-600 border-none font-medium hover:bg-blue-500/20 text-xs">{theme}</Badge>
                    ))}
                  </div>
                </CardContent>
              </Card>

              <Card className="shadow-sm border-border/40">
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2"><Users className="h-5 w-5 text-purple-500" /> Target Audience</CardTitle>
                </CardHeader>
                <CardContent className="text-sm leading-relaxed text-foreground/80 font-medium">
                  {creator.aiInsights?.audienceArchetype}
                </CardContent>
              </Card>
            </div>
          </div>

          <Card className="shadow-sm border-border/40 bg-gradient-to-br from-orange-500/5 to-transparent">
            <CardHeader>
              <CardTitle className="text-lg flex items-center gap-2"><Zap className="h-5 w-5 text-orange-500" /> Hook Strategy Analysis</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm sm:text-base leading-relaxed text-foreground/80 font-medium italic">
                &quot;{creator.aiInsights?.hookAnalysis}&quot;
              </p>
            </CardContent>
          </Card>

          {creator.aiInsights?.strongVsGoodPoints && (
            <div className="mt-8 border border-border/50 rounded-3xl p-6 sm:p-10 bg-card shadow-sm overflow-x-auto">
              <MarkdownContent content={creator.aiInsights.strongVsGoodPoints} variant="analysis" />
            </div>
          )}
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center p-12 text-center bg-muted/20 border border-dashed rounded-3xl">
          <Sparkles className="h-10 w-10 text-orange-500/30 mb-4" />
          <h3 className="text-lg font-bold">No Deep Analysis Available</h3>
          <p className="text-sm text-muted-foreground mt-2 max-w-md">This creator's profile has been scanned, but the deep AI analysis hasn't been generated yet.</p>
        </div>
      )}

      {/* Top Performances */}
      <div className="space-y-6 pt-10 border-t border-border/30">
        <h2 className="text-2xl font-black flex items-center gap-2"><PlayCircle className="h-6 w-6 text-blue-500" /> Top Reels</h2>
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-3">
          {topPerformances.map((post) => (
            <div key={post.postId} className="relative aspect-[10/16] bg-black/5 overflow-hidden rounded-xl group border border-border/40 shadow-sm hover:border-orange-500/30 transition-colors">
              {post.thumbnailUrl ? (
                <img src={`/api/proxy-image?url=${encodeURIComponent(post.thumbnailUrl)}`} alt="Reel" className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" />
              ) : (
                <div className="w-full h-full flex items-center justify-center bg-muted"><Film className="h-6 w-6 opacity-20" /></div>
              )}
              <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent" />
              <a href={post.videoUrl || `https://instagram.com/reel/${post.postId}`} target="_blank" rel="noreferrer" className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity bg-black/20 backdrop-blur-[2px]">
                <PlayCircle className="h-10 w-10 text-white drop-shadow-lg" />
              </a>
              <div className="absolute bottom-0 left-0 right-0 p-3">
                <span className="text-white font-bold text-xs flex items-center gap-1.5 drop-shadow-md">
                  <Eye className="h-3 w-3 text-orange-400" /> {formatNumber(post.videoPlayCount)}
                </span>
                {post.caption && <p className="text-[9px] text-white/70 line-clamp-2 mt-1">{post.caption}</p>}
              </div>
            </div>
          ))}
          {topPerformances.length === 0 && <p className="text-muted-foreground text-sm col-span-full">No performances tracked yet.</p>}
        </div>
      </div>

      {/* Viral Growth Loop CTA */}
      <div className="mt-16 bg-gradient-to-br from-orange-500 to-rose-600 rounded-3xl p-8 sm:p-12 text-center text-white shadow-2xl relative overflow-hidden">
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay"></div>
        <div className="relative z-10 max-w-2xl mx-auto space-y-6">
          <h2 className="text-3xl sm:text-4xl font-black">Want to analyze your own profile?</h2>
          <p className="text-lg text-white/80 font-medium">Stop guessing what works. Discover your exact flaws and see how your strategy compares against the top 1% of creators.</p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4">
            <Button asChild size="lg" className="bg-white text-orange-600 hover:bg-gray-50 rounded-xl h-14 px-8 text-base font-bold w-full sm:w-auto shadow-xl">
              <Link href="/profile">Connect Instagram</Link>
            </Button>
            <Button asChild size="lg" variant="outline" className="border-white/30 text-white hover:bg-white/10 rounded-xl h-14 px-8 text-base font-bold w-full sm:w-auto backdrop-blur-sm">
              <Link href="/">Start Free Analysis</Link>
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
